dash/urls.py
from django.urls import path

from . import views 

app_name = 'dash'

urlpatterns = [
    path('main_dash/', views.main_dash, name='main_dash'),
    path('summary/', views.summary_dash, name ='summary'),
    path('mortality/',views.mortality, name ='mortality'),
    # path('summary-chart',views.summary_chart, name ='summary-chart'),
]

pml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pmlmain.urls')),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('pmlprofile/', include('pmlprofile.urls'), name='pmlprofile'),
    path('events/',include('events.urls'), name='events'),
    path('docs/', include('docs.urls'), name='docs'),
    path('geoApp/', include('geoApp.urls'), name='geoApp'),
    path('dash/', include('dash.urls'), name='dash'),
    path('pmlfin/', include('pmlfin.urls'), name='pmlfin'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
admin.site.site_header ='PML Admin Portal' 
admin.site.index_title ='Manage the PML Portal'

pmlfin/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'pmlfin'

urlpatterns = [
    path('member-accounts/', views.member_accounts, name='member-accounts'),
    path('cashflow/', views.cashflow, name='cashflow'),
    path('shares/', views.shares_view, name='shares'),
    path('acc_detail/<int:pk>/', views.AccountDetail.as_view(), name='acc_detail'),
    path('acc_print/<int:pk>/', views.AccountDetailPrint.as_view(), name='acc_print'),
    path('wealth/',views.net_wealth, name='wealth')
]

pmlprofile/urls.py
from django.urls import path
from .views import (ProfileListView, CommitteeListView, IncumbentUpdateView,
                    MyProfileView, ProfileCertView, BeneficiaryList, #MemberAccountView,
                    ProfileDetails, CommitteeDetail, IncumbentCreateView,
                    UserLoginAdminView,
                    )                
from .views import profile_update, pdfcert_view, membercert_view

from django.contrib.auth.decorators import login_required

app_name = 'pmlprofile'  

urlpatterns =[
    # path('member_list/',views.member_list_view, name='member_list'),
    path('beneficiaries/',BeneficiaryList.as_view(), name= 'beneficiaries'),
    path('profiles/',ProfileListView.as_view(), name = 'profiles'),
    path('profile_detail/<int:pk>/',ProfileDetails.as_view(), name='profile_detail'),
    path('my_profile/<int:pk>/',login_required(MyProfileView.as_view(template_name='pmlprofile/my_profile.html')), name='my_profile'),
    path('my_cert/<int:pk>/',ProfileCertView.as_view(), name='my_cert'),
    path('pdf_cert/<int:pk>',pdfcert_view, name='pdf_cert'),
    path('membercert/<int:pk>/',membercert_view, name='membercert'),
    path('user_logins/', UserLoginAdminView.as_view(), name='user_login_admin'),
    # path('profile_dash/',profile_dash, name='profile_dash'),
    # path('ben_dash/',ben_dash, name='ben_dash'),
    # path('member_accounts/', MemberAccountView.as_view(), name='member_accounts'),
    
    # path('pdf_certificate/', views.pdf_certificate, name='pdf-certificate'),
    # path('my_cert/pdf_cert/<int:pk>/',views.pdfcert_view, name='pdf_cert'),
    # path('profile/add/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile_update/',profile_update, name='profile_update'),
    path('committees/',CommitteeListView.as_view(), name = 'committees'),
    path('committees/<int:pk>/',CommitteeDetail.as_view(), name = 'committee_detail'),
    path('committee_create/', IncumbentCreateView.as_view(), name='committee_create'),
    path('committee_update/<int:pk>/', IncumbentUpdateView.as_view(), name='committee_update')
    # path('committee_update/')
]

pmlfin/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime, date
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from collections import Counter

import pandas as pd 
import numpy as np
import calendar
import json
from django.http import JsonResponse

from .models import MemberAccount, Cashflow, Company, Share, Wealth
from pmlprofile.models import Profile

# Member  accounts list
@login_required
def member_accounts(request):
    
    first_rec = MemberAccount.objects.all()[0]

    max_date = MemberAccount.objects.latest("date").date
    latest_accounts = MemberAccount.objects.filter(date=max_date)   
    context ={
        'latest_accounts': latest_accounts,
        'first_rec': first_rec,
    }
    
    return render(request, 'pmlfin/member-accounts.html', context)

# Member individual acconts
class AccountDetail(LoginRequiredMixin, DetailView):
    context_object_name = 'member_account'
    model = Profile
    template_name = 'pmlfin/account-detail.html'
    
    def get_object(self):
        return self.model.objects.get(pk=self.request.user.pk)
    
    def get_context_data(self, *args, **kwargs):    
        context = super(AccountDetail, self).get_context_data(*args, **kwargs)
        context['today'] = date.today()
        return context  

class AccountDetailPrint(LoginRequiredMixin, DetailView):
    context_object_name = 'member_account'
    model = Profile
    template_name = 'pmlfin/account-print.html'
    
    def get_object(self):
        return self.model.objects.get(pk=self.request.user.pk)
    
    def get_context_data(self, *args, **kwargs):    
        context = super(AccountDetailPrint, self).get_context_data(*args, **kwargs)
        context['today'] = date.today()
        return context  
    
# Monthly cashflow analysis
@login_required
def cashflow(request):
    cash_qs = Cashflow.objects.order_by('date')
    cash_qs1 = cash_qs.values('date','opening_bank_bal','expenses','income','closing_bank_bal')
    cash_df = pd.DataFrame.from_records(cash_qs1)

    cash_df['year'] = pd.DatetimeIndex(cash_df['date']).year
    cash_df['month_int'] =pd.DatetimeIndex(cash_df['date']).month
    cash_df['month'] = cash_df['month_int'].apply(lambda x: calendar.month_abbr[x])
    cash_df['cash'] = cash_df['closing_bank_bal'].astype(float)
    cash_df['expenses'] = cash_df['expenses'].astype(float)
    cash_df['income'] = cash_df['income'].astype(float)
    cash_df['month_year'] = cash_df['month'] + ' ' + cash_df['year'].astype(str)  
    mean_closing_bal = cash_df['closing_bank_bal'].mean()
    max_closing_bal = cash_df['closing_bank_bal'].max()
    min_closing_bal = cash_df['closing_bank_bal'].min()
    
    mean_expenses = cash_df['expenses'].mean()
    max_expenses = cash_df['expenses'].max()
    min_expenses = cash_df['expenses'].min()
    
    mean_income = cash_df['income'].mean()
    max_income = cash_df['income'].max()
    min_income = cash_df['income'].min()
    
    max_month = cash_df.loc[cash_df['closing_bank_bal'] == max_closing_bal, 'month_year'].item()
    
    max_month_income = cash_df.loc[cash_df['income'] == max_income, 'month_year'].item()
    max_month_expenses = cash_df.loc[cash_df['expenses'] == max_expenses, 'month_year'].item()
    
    
    min_month = cash_df.loc[cash_df['closing_bank_bal'] == min_closing_bal, 'month_year'].item()
    
    min_month_income = cash_df.loc[cash_df['income'] == min_income, 'month_year'].item()
    min_month_expenses = cash_df.loc[cash_df['expenses'] == min_expenses, 'month_year'].iloc[0]
    
    date_list = list(cash_df['month_year'])[-12:]
    date_list2 = list(cash_df['month_year'])[-12:]
    
    date_range = (date_list[0], date_list[-1])
    # print(date_list)
    cash_list = list(cash_df['cash'])[-12:]
    
    date_from = date_range[0]
    date_to = date_range[1]
    
    expenses_list = list(cash_df['expenses'])[-12:]
    income_list = list(cash_df['income'])[-12:]
    
    context={
        'cash_qs': cash_qs,
        'date_list': date_list,
        'cash_list': cash_list,
        'date_list2': date_list2,
        'income_list': income_list,
        'expenses_list': expenses_list,
        'mean_closing_bal': mean_closing_bal,
        'max_closing_bal': max_closing_bal,
        'min_closing_bal': min_closing_bal,
        'date_from': date_from,
        'date_to': date_to,
        'min_month': min_month,
        'max_month': max_month,
        'mean_expenses': mean_expenses,
        'max_expenses': max_expenses,
        'min_expenses': min_expenses,
        'mean_income': mean_income,
        'max_income': max_income,
        'min_income': min_income,
        'max_month_income': max_month_income,
        'max_month_expenses': max_month_expenses,
        'min_month_income': min_month_income,
        'min_month_expenses': min_month_expenses,
    }
    
    return render(request, 'pmlfin/cash-balance.html',context)

# Shares investment  analysis
def shares_view(request):
    qs_co = Company.objects.all()
    qs_co1 = qs_co.values('logo','name','trading_name', 'purchase_date',
                            'num_shares','purchase_price','purchase_value')
    
    co_df = pd.DataFrame.from_records(qs_co1)
    co_df['pur_price'] = co_df['purchase_value'].astype(float)


    name_list = list(co_df['name'])
    trade_name_list = list(co_df['trading_name'])
    purchase_value_list = list(co_df['pur_price'])
    num_shares_list = list(co_df['num_shares'])
    total_purchase_value = co_df['pur_price'].sum()
    share_qs = Share.objects.all()
    qs = share_qs.values('date','company','current_share_price','current_value')
    
    share_df = pd.DataFrame.from_records(qs)
    share_df['year'] = pd.DatetimeIndex(share_df['date']).year
    share_df['int_month'] = pd.DatetimeIndex(share_df['date']).month
    share_df['month'] = share_df['int_month'].apply(lambda x: calendar.month_abbr[x])
    share_df['month_year'] = share_df['month'] + '-' + share_df['year'].astype(str)
    
    share_df['curr_value'] = share_df['current_value'].astype(float)
    
    share_labels = share_df['month_year'].unique().tolist()[-12:]
    
    mtn_df = share_df.loc[share_df['company'] == 1]
    mtn_values = list(mtn_df['curr_value'])[-12:]
    
    sol_df = share_df.loc[share_df['company'] == 2]
    sol_values = list(sol_df['curr_value'])[-12:]
    
    solbe_df = share_df.loc[share_df['company'] == 3]
    solbe_values = list(solbe_df['curr_value'])[-12:]
    
    telkom_df = share_df.loc[share_df['company'] == 4]
    telkom_values = list(telkom_df['curr_value'])[-12:]
    
    vod_df = share_df.loc[share_df['company'] == 5]
    vod_values = list(vod_df['curr_value'])[-12:]

    phuthuma_df = share_df.loc[share_df['company'] == 6]
    phuthuma_values = list(phuthuma_df['curr_value'])[-12:]

    yebo_df = share_df.loc[share_df['company'] == 7]
    yebo_values = list(yebo_df['curr_value'])[-12:]

    latest_date = Share.objects.latest("date").date
    latest_share = Share.objects.filter(date=latest_date) 
    # df = pd.DataFrame.from_records(list(latest_share.values()))
    # print(df)
    latest_qs = latest_share.values('company','date','current_share_price','current_value')
    latest_df = pd.DataFrame.from_records(latest_qs)
    
    latest_df['curr_value'] = latest_df['current_value'].astype(float)
    total_share_value = latest_df['curr_value'].sum() 

    current_value_list = list(latest_df['curr_value'])
    
    context = {
        'qs_co': qs_co,
        'trade_name_list': trade_name_list,
        'purchase_value_list': purchase_value_list,
        'total_purchase_value': total_purchase_value,
        'current_value_list': current_value_list,
        'total_share_value': total_share_value,
        'mtn_values': mtn_values,
        'sol_values': sol_values,
        'solbe_values': solbe_values,
        'telkom_values': telkom_values,
        'vod_values': vod_values,
        'phuthuma_values': phuthuma_values,
        'yebo_values': yebo_values,
        'share_labels': share_labels,
    }
    
    return render(request, 'pmlfin/shares.html', context)

# Net Wealth analysis 
def net_wealth(request):
    qs = Wealth.objects.all()
    qs1 = qs.values('date','closing_cash_balance','notice_acc_balance',
                    'monthly_shares_total','total_net_wealth')
    
    wealth_df = pd.DataFrame.from_records(qs1)

    wealth_df['latest_date'] = wealth_df['date'].astype(str)
    wealth_df['bank_bal'] = wealth_df['closing_cash_balance'].astype(float)
    wealth_df['notice_bal'] = wealth_df['notice_acc_balance'].astype(float)
    wealth_df['shares_total'] = wealth_df['monthly_shares_total'].astype(float)
    wealth_df['tot_net_wealth'] = wealth_df['total_net_wealth'].astype(float)
    
    wealth_df['year'] = pd.DatetimeIndex(wealth_df['date']).year
    wealth_df['month_int'] =pd.DatetimeIndex(wealth_df['date']).month
    wealth_df['month'] = wealth_df['month_int'].apply(lambda x: calendar.month_abbr[x])  
    wealth_df['month_year'] = wealth_df['month'] + '-' + wealth_df['year'].astype(str)
    
    bank_bal_list = list(wealth_df['bank_bal'])[-6:]
    notice_bal_list = list(wealth_df['notice_bal'])[-6:]
    shares_total_list = list(wealth_df['shares_total'])[-6:]
    net_wealth_list = list(wealth_df['tot_net_wealth'])[-6:]
    date_list = list(wealth_df['latest_date'])[-6:]
    wealth_date_list = list(wealth_df['month_year'])[-6:]
    wealth_date_range = (wealth_date_list[0], wealth_date_list[-1])
    wealth_date_from = wealth_date_range[0]
    wealth_date_to = wealth_date_range[-1]
    
    net_wealth_average = wealth_df['tot_net_wealth'].mean().astype(float)
    net_wealth_high = wealth_df['tot_net_wealth'].max().astype(float)
    net_wealth_low = wealth_df['tot_net_wealth'].min().astype(float)
    

templates/pmlfin/account-detail.html
{% extends 'layout.html' %}
{% load humanize %}
{% load static %}

{% block title %}|{{member_account.shortname}} Acc as at
{% for obj in member_account.profile.all %}
{% if forloop.first %}
{{ obj.date|date:'d M Y'}}
{% endif %}
{% endfor %} 
{% endblock title %}


{% block content %}

<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Member Account Statement as at 
            <b> 
                {% for obj in member_account.profile.all %}
                {% if forloop.first %}
                    {{ obj.date|date:'d M Y'}}
                {% endif %}
                {% endfor %}
            </b> 
        </h1> 
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'pmlprofile:profiles'%}">Membership</a></li>
            <li class="breadcrumb-item active">{{ member_account.shortname}} Account</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
    <div class="row">
        <div class="col-12">
        <!-- Main content -->
        {% if user.is_authenticated %} 
        <div class="invoice p-3 mb-3">
            <!-- title row -->
            <div class="row">
                <div class="col-12">
                    <h4>
                        <div class= "text-center">
                            <img src="{% static 'img/pml-logo1.png' %}" alt="PML Logo" height="80" width="120" >
                        </div>
                        <small class="float-left" style = "text-decoration: underline; 
                            font-style: italic; font-weight: bold"> 
                            Member Ref.: PML1991-{{member_account.id}}{{member_account.user.first_name|slice:1}}{{member_account.middlename|slice:1}}
                        </small>
                        <small class="float-right" style = "text-decoration: underline; 
                            font-style: italic; font-weight: bold">
                            Statement Date: {{today|date:'d F Y'}} 
                        </small>
                    </h4> 
                </div>

            <!-- /.col -->
            </div>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <!-- info row -->
            <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
                <span style= "font-style:italic; text-decoration: 
                            underline; font-weight: bold; color:rgb(9, 76, 177)"> 
                    Payments due to:
                </span>     
                <address>
                <strong>Progress Men's League</strong><br>
                Private Bag X709<br>
                EKANGALA, 1021 <br>
                Phone: +27 82 736 6495 &nbsp;&nbsp;|&nbsp;&nbsp; Email: <a href="mailto:treasury@progressmensleague.org">treasury@progressmensleague.org </a>               
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <span style= "font-style:italic; text-decoration: underline;
                        font-weight: bold; color:rgb(9, 76, 177)"> 
                    Account Information:
                </span>  
                <address>
                <strong> Mr. {{member_account.user.first_name}}  
                    {% if member_account.middlename == None %} 
                    {% else %} 
                    {{member_account.middlename}}
                    {% endif %}
                    {{member_account.user.last_name}}
                </strong><br>
                {{member_account.address}}<br>
                {{member_account.town_city}}<br>
                Phone: {{member_account.mobile_phone}} &nbsp;&nbsp;&nbsp;|&nbsp;
                Email: <a href="mailto:{{member_account.user.email}}"> {{member_account.user.email}}</a>  
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <span style= "font-style:italic; text-decoration: underline;
                font-weight: bold; color:rgb(9, 76, 177)"> 
                <b>Banking Details</b><br>
            </span>
                <b>Bank: First National Bank </b> <br>
                    Acc No.: 620 242 992 33 <br>
                    Acc Type: Current - Gold Business<br>
                    Branch: Bronkhorstspruit<br>      
            </div>
            <!-- /.col -->
            </div>
            <!-- /.row -->
            <!-- <hr style="height:1px;border-width:0;color:gray;background-color:gray"> -->
            <!-- Table row -->
            <div class="row">
            <div class="col-12 table-responsive">
                <table class="table table-striped table-bordered">
                <thead>
                <tr class="bg-light" >  
                    <th colspan="2" class="text-center" style="border-left:solid; border-top:solid;">PRIOR BALANCE(B/F)</th>       
                    <th colspan="5" class="text-center" style=" border-right:solid; border-left:solid;border-top:solid">DEBITS</th>
                    <th colspan="3" class="text-center" style="border-right:solid; border-left:solid;border-top:solid">RECEIPTS</th>
                    <th style="border-right:solid; border-left:solid;border-top:solid">OUTSTANDING/SURPLUS</th>
                </tr>
                <tr>
                    <th style="border-left:solid">Date</th>
                    <th>Balance BF</th>
                    <th style="border-left:solid">Premiums</th>
                    <th>Funeral </th>
                    <th>Transport</th>
                    <th>Fines</th>
                    <th style="border-right:solid">Tot Debits</th>
                    <th>Deposits</th>
                    <th>Adjustments</th>
                    <th style="border-right:solid">Tot Receipts</th>
                    <th style="border-right:solid">Closing Balance</th>
                </tr>
                </thead>
                <tbody>
                {% for acc in member_account.profile.all|slice:":3" %}
                <tr>
                    <td style="border-left:solid">{{acc.date|date:'d F Y'}}</td>
                    <td>{{acc.balance_brought_forward}}</td>
                    <td style="border-left:solid">{{acc.premiums}}</td>
                    <td>{{acc.funeral_topup}}</td>
                    <td>{{acc.transport_topup}}</td>
                    <td>{{acc.fines}}</td>
                    <th style="border-right:solid">{{acc.total_debits}}</th>
                    <td>{{acc.cash_deposit}}</td>
                    <td>{{acc.adjustments}}</td>
                    <th style="border-right:solid">{{acc.total_receipts}}</th>
                    <th style="border-right:solid">{{acc.total_outstanding|floatformat:2|intcomma}}</th>
                </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
            <!-- /.col -->
            </div>
            <!-- /.row -->
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <div class="row">
            <!-- accepted payments column -->
            <div class="col-6">
                <div class="text-muted">       
                    <h6 class="alert alert-light"> <span style="text-decoration: underline">
                                Important Note: </span>
                        &nbsp;&nbsp;&nbsp; 
                        A positive( > 0 ) balance amount means your account is in 
                        <b class="text-danger">arrears </b>. Please remit asap.                  
                    </h6> 
                        
                </div>
            </div>
            <!-- /.col -->
            <div class="col-6">
                <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th colspan="2" class="text-center" style="background-color: rgb(235, 232, 232)">
                            Latest Account Summary: 
                            {% for obj in member_account.profile.all %}
                                {% if forloop.first %}
                                {{ obj.date|date:'M Y'}}
                                {% endif %}
                            {% endfor %} 
                        </th>
                    </thead>
                    <tr>
                    <td style="width:50%">Net Movement</td>
                    <td>
                        <b> 
                            {% for obj in member_account.profile.all %}
                            {% if forloop.first %}
                                R {{ obj.net_movement|floatformat:2|intcomma}}
                            {% endif %}
                            {% endfor %}
                        </b> 

                    </td>
                    </tr>
                    <tr>
                    <td>Outstanding/Surplus</td>
                    <td>
                        <b> 
                            {% for obj in member_account.profile.all %}
                                {% if forloop.first %}
                                    {% if obj.total_outstanding < 0 %}
                                        <span class="text-primary">R {{ obj.total_outstanding|floatformat:2|intcomma}}</span>
                                    
                                    {% elif obj.total_outstanding > 0 and obj.total_outstanding < 500.00 %}
                                        <span class="text-secondary">R {{ obj.total_outstanding|floatformat:2|intcomma}}</span>
                                    {% elif obj.total_outstanding >= 500.00 and obj.total_outstanding < 1000.00 %}
                                        <span style="color:rgb(216, 156, 4)">R {{ obj.total_outstanding|floatformat:2|intcomma}}</span>
                                    {% else %} 
                                        <span class="text-danger">R {{ obj.total_outstanding|floatformat:2|intcomma}}</span>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </b> 

                    </td>
                    </tr>
                </table>
                
                </div>
            </div>
            <!-- /.col -->
            

            </div>

            <!-- Print pdf -->

            <div class="row no-print">
                <div class="col-12">
                  <a href="{% url 'pmlfin:acc_print' request.user.id %}" rel="noopener" target="_blank" type="button" type="button" class="btn btn-info float-right"><i class="fas fa-print"></i> Print Statement</a>
                  
                </div>
              </div>

            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <!-- /.row -->

            <!-- this row will not appear when printing -->
    
        </div>
        
        {% endif %}
        <!-- /.invoice -->
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
{% endblock content %}