pml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pmlmain.urls')),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('pmlprofile/', include('pmlprofile.urls'), name='pmlprofile'),
    path('events/',include('events.urls'), name='events'),
    path('docs/', include('docs.urls'), name='docs'),
    path('geoApp/', include('geoApp.urls'), name='geoApp'),
    path('dash/', include('dash.urls'), name='dash'),
    path('pmlfin/', include('pmlfin.urls'), name='pmlfin'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
admin.site.site_header ='PML Admin Portal' 
admin.site.index_title ='Manage the PML Portal'

pmladmin/urls.py
from django.urls import path

pmlprofile/urls.py
from django.urls import path
from .views import (ProfileListView, CommitteeListView, IncumbentUpdateView,
                    MyProfileView, ProfileCertView, BeneficiaryList, #MemberAccountView,
                    ProfileDetails, CommitteeDetail, IncumbentCreateView,
                    UserLoginAdminView,
                    )                
from .views import profile_update, pdfcert_view, membercert_view

from django.contrib.auth.decorators import login_required

app_name = 'pmlprofile'  

urlpatterns =[
    # path('member_list/',views.member_list_view, name='member_list'),
    path('beneficiaries/',BeneficiaryList.as_view(), name= 'beneficiaries'),
    path('profiles/',ProfileListView.as_view(), name = 'profiles'),
    path('profile_detail/<int:pk>/',ProfileDetails.as_view(), name='profile_detail'),
    path('my_profile/<int:pk>/',login_required(MyProfileView.as_view(template_name='pmlprofile/my_profile.html')), name='my_profile'),
    path('my_cert/<int:pk>/',ProfileCertView.as_view(), name='my_cert'),
    path('pdf_cert/<int:pk>',pdfcert_view, name='pdf_cert'),
    path('membercert/<int:pk>/',membercert_view, name='membercert'),
    path('user_logins/', UserLoginAdminView.as_view(), name='user_login_admin'),
    # path('profile_dash/',profile_dash, name='profile_dash'),
    # path('ben_dash/',ben_dash, name='ben_dash'),
    # path('member_accounts/', MemberAccountView.as_view(), name='member_accounts'),
    
    # path('pdf_certificate/', views.pdf_certificate, name='pdf-certificate'),
    # path('my_cert/pdf_cert/<int:pk>/',views.pdfcert_view, name='pdf_cert'),
    # path('profile/add/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile_update/',profile_update, name='profile_update'),
    path('committees/',CommitteeListView.as_view(), name = 'committees'),
    path('committees/<int:pk>/',CommitteeDetail.as_view(), name = 'committee_detail'),
    path('committee_create/', IncumbentCreateView.as_view(), name='committee_create'),
    path('committee_update/<int:pk>/', IncumbentUpdateView.as_view(), name='committee_update')
    # path('committee_update/')
]

pmladmin/models.py
from django.db import models

pmladmin/forms.py
from django import forms


        

        
        

pmladmin/views.py
from django.shortcuts import render, redirect
# from pmlfin.models import MemberAccount, Cashflow, Company,Share, Wealth

templates/pmladmin/member_account.html
{% extends 'layout.html' %}

{% block title %} | My Account {% endblock %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Account Statement : {{my_acc.member}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active"></li> {{member_acc.member.user.last_name}} Statement</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="callout callout-info">
              <h5><i class="fas fa-info"></i> Note:</h5>
              This page has been enhanced for printing. Click the print button at the bottom of the invoice to test.
            </div>


            <!-- Main content -->
            <div class="invoice p-3 mb-3">
              <!-- title row -->
              <div class="row">
                <div class="col-12">
                  <h4>
                    <i class="fas fa-globe"></i> AdminLTE, Inc.
                    <small class="float-right">Date: 2/10/2014</small>
                  </h4>
                </div>
                <!-- /.col -->
              </div>
              <!-- info row -->
              <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                  From
                  <address>
                    <strong>Admin, Inc.</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (804) 123-5432<br>
                    Email: info@almasaeedstudio.com
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  To
                  <address>
                    <strong>John Doe</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (555) 539-1037<br>
                    Email: john.doe@example.com
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  <b>Invoice #007612</b><br>
                  <br>
                  <b>Order ID:</b> 4F3S8J<br>
                  <b>Payment Due:</b> 2/22/2014<br>
                  <b>Account:</b> 968-34567
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- Table row -->
              <div class="row">
                <div class="col-12 table-responsive">
                  <table class="table table-striped">
                    <thead>
                    <tr>
                      <th>Qty</th>
                      <th>Product</th>
                      <th>Serial #</th>
                      <th>Description</th>
                      <th>Subtotal</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                      <td>1</td>
                      <td>Call of Duty</td>
                      <td>455-981-221</td>
                      <td>El snort testosterone trophy driving gloves handsome</td>
                      <td>$64.50</td>
                    </tr>
                    <tr>
                      <td>1</td>
                      <td>Need for Speed IV</td>
                      <td>247-925-726</td>
                      <td>Wes Anderson umami biodiesel</td>
                      <td>$50.00</td>
                    </tr>
                    <tr>
                      <td>1</td>
                      <td>Monsters DVD</td>
                      <td>735-845-642</td>
                      <td>Terry Richardson helvetica tousled street art master</td>
                      <td>$10.70</td>
                    </tr>
                    <tr>
                      <td>1</td>
                      <td>Grown Ups Blue Ray</td>
                      <td>422-568-642</td>
                      <td>Tousled lomo letterpress</td>
                      <td>$25.99</td>
                    </tr>
                    </tbody>
                  </table>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <div class="row">
                <!-- accepted payments column -->
                <div class="col-6">
                  <p class="lead">Payment Methods:</p>
                  <img src="../../dist/img/credit/visa.png" alt="Visa">
                  <img src="../../dist/img/credit/mastercard.png" alt="Mastercard">
                  <img src="../../dist/img/credit/american-express.png" alt="American Express">
                  <img src="../../dist/img/credit/paypal2.png" alt="Paypal">

                  <p class="text-muted well well-sm shadow-none" style="margin-top: 10px;">
                    Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem
                    plugg
                    dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
                  </p>
                </div>
                <!-- /.col -->
                <div class="col-6">
                  <p class="lead">Amount Due 2/22/2014</p>

                  <div class="table-responsive">
                    <table class="table">
                      <tr>
                        <th style="width:50%">Subtotal:</th>
                        <td>$250.30</td>
                      </tr>
                      <tr>
                        <th>Tax (9.3%)</th>
                        <td>$10.34</td>
                      </tr>
                      <tr>
                        <th>Shipping:</th>
                        <td>$5.80</td>
                      </tr>
                      <tr>
                        <th>Total:</th>
                        <td>$265.24</td>
                      </tr>
                    </table>
                  </div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- this row will not appear when printing -->
              <div class="row no-print">
                <div class="col-12">
                  <a href="invoice-print.html" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                  <button type="button" class="btn btn-success float-right"><i class="far fa-credit-card"></i> Submit
                    Payment
                  </button>
                  <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                    <i class="fas fa-download"></i> Generate PDF
                  </button>
                </div>
              </div>
            </div>
            <!-- /.invoice -->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock %}

templates/pmladmin/member_accounts.html
{% extends 'layout.html' %}

{% block title %} Member Accounts{% endblock %}

{% block content %}

<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Member Individual Accounts</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Accounts</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
    <div class="card-header">

        <h3 class="card-title">Summary of Member Accounts</h3>

        <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
        </button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
        </button>
        </div>
    </div>
    <div class="card-body">
        <div class="jumbotron">          
            
            {% for account in accounts %}
             <p> Account Name: {{ account.member}} {{account.total_outstanding}} </p>
           
            {% endfor %}

            
            <table class="table table-striped">
            <thead>

                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Month</th>
                <th scope="col">Total Outstanding</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                <tr>
                <th scope="row">{{account.id}}</th>
                <td>{{account.member.user.last_name}} {{account.member.user.first_name}} {{account.member.middlename}}</td>
                <td>{{account.month_date|date:'M -Y'}}</td>
                <td>{{account.total_outstanding}}</td>
                </tr>
                {% endfor %}
            </tbody>
            </table>


        </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        Footer
    </div>
    <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

templates/pmladmin/members.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %} 

{% block content %} 

<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Members</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'pmlprofile:profiles' %}">PML Profiles</a></li>
            <li class="breadcrumb-item active">Members</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
    <!-- Default box -->
      <!-- Beneficiary Data Table -->
<section class="content">
<div class="container-fluid">
    <div class="row">
    <div class="col-12">
        <div class="card">
        <div class="card-header">
            <h3 class="card-title">All Member Profiles</h3>
        </div>
    <div class="card-body">
        <table id="example2" class="table table-bordered table-hover">
            <thead>
                <tr>
                    
                    <th ">
                    Full Name
                    </th>
                    <th ">
                    Birth Date
                    </th>
                    <th >
                    Mobile Phone
                    </th>
                    <th >
                   Status
                    </th> 
                    <th >
                   Status Date
                    </th> 
                    
                    <th  class="project-actions text-right"> 
                        <a class="btn btn-success btn-sm" href="{% url 'pmlprofile:committee_create' %}">
                            <i class="fas fa-plus-circle">
                            </i>
                        <strong> Add Member</strong>
                        </a> 
                    </th>                
                </tr>
            </thead>
            <tbody>
                <tr>
            {% for member in members %}
                    <td>
                        {{ member.user.last_name}}  {{ member.user.first_name }}  
                        {% if member.middlename == None %} 
                        {{ ''}}
                        {% else %}
                        {{ member.middlename}}
                        {% endif %}
                    </td>
                    <td>
                        {{member.birth_date|date:'d M Y'}}
                    </td>
                    <td>
                        {{member.mobile_phone}}
                    </td>

                    <td>
                        {{member.status}}
                    </td>
                    <td>
                    {{ member.status_date|date:'d M Y'}}
                    </td>

                    <td class="project-actions text-right">
                    <ul class="list-inline"> 
                        <a class="btn btn-primary btn-sm" href="">
                            <i class="fas fa-folder">
                            </i>
                            View
                        </a>
                        <a class="btn btn-info btn-sm" href="#">
                            <i class="fas fa-pencil-alt">
                            </i>
                            Edit
                        </a> 
                    </ul>
                            
                    </td>
                </tr>   
        {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <!-- <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> -->
            </div>
    <!-- /.card -->
         </div>
    <!-- /.col -->
        </div>
    <!-- /.row -->
   
<!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>

<!-- /.content-wrapper -->
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip(); 
});
</script>
{% endblock %}