pml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pmlmain.urls')),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('pmlprofile/', include('pmlprofile.urls'), name='pmlprofile'),
    path('events/',include('events.urls'), name='events'),
    path('docs/', include('docs.urls'), name='docs'),
    path('geoApp/', include('geoApp.urls'), name='geoApp'),
    path('dash/', include('dash.urls'), name='dash'),
    path('pmlfin/', include('pmlfin.urls'), name='pmlfin'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
admin.site.site_header ='PML Admin Portal' 
admin.site.index_title ='Manage the PML Portal'

pmlprofile/urls.py
from django.urls import path
from .views import (ProfileListView, CommitteeListView, IncumbentUpdateView,
                    MyProfileView, ProfileCertView, BeneficiaryList, #MemberAccountView,
                    ProfileDetails, CommitteeDetail, IncumbentCreateView,
                    UserLoginAdminView,
                    )                
from .views import profile_update, pdfcert_view, membercert_view

from django.contrib.auth.decorators import login_required

app_name = 'pmlprofile'  

urlpatterns =[
    # path('member_list/',views.member_list_view, name='member_list'),
    path('beneficiaries/',BeneficiaryList.as_view(), name= 'beneficiaries'),
    path('profiles/',ProfileListView.as_view(), name = 'profiles'),
    path('profile_detail/<int:pk>/',ProfileDetails.as_view(), name='profile_detail'),
    path('my_profile/<int:pk>/',login_required(MyProfileView.as_view(template_name='pmlprofile/my_profile.html')), name='my_profile'),
    path('my_cert/<int:pk>/',ProfileCertView.as_view(), name='my_cert'),
    path('pdf_cert/<int:pk>',pdfcert_view, name='pdf_cert'),
    path('membercert/<int:pk>/',membercert_view, name='membercert'),
    path('user_logins/', UserLoginAdminView.as_view(), name='user_login_admin'),
    # path('profile_dash/',profile_dash, name='profile_dash'),
    # path('ben_dash/',ben_dash, name='ben_dash'),
    # path('member_accounts/', MemberAccountView.as_view(), name='member_accounts'),
    
    # path('pdf_certificate/', views.pdf_certificate, name='pdf-certificate'),
    # path('my_cert/pdf_cert/<int:pk>/',views.pdfcert_view, name='pdf_cert'),
    # path('profile/add/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile_update/',profile_update, name='profile_update'),
    path('committees/',CommitteeListView.as_view(), name = 'committees'),
    path('committees/<int:pk>/',CommitteeDetail.as_view(), name = 'committee_detail'),
    path('committee_create/', IncumbentCreateView.as_view(), name='committee_create'),
    path('committee_update/<int:pk>/', IncumbentUpdateView.as_view(), name='committee_update')
    # path('committee_update/')
]

pmlprofile/forms.py
from django import forms 
from django.forms import ModelForm, Textarea
from django.contrib.auth.models import User
from .models import Profile
from crispy_forms.helper import FormHelper


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']
        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['shortname', 'middlename', 'birth_date', 'mobile_phone','alt_phone', 'photo','address','alt_address','town_city' ,'district_metro','province']
        date_field = forms.DateField(
                    widget=forms.TextInput(     
                    attrs={'type': 'date'} 
                        )
                    )        

pmlprofile/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView,DetailView
from datetime import datetime, date
from django.db.models import Count
from django.contrib.auth.models import User
                                
from django.views.generic.edit import UpdateView, CreateView
from .models import Profile, Beneficiary, Committee, Incumbent 
#MemberAccount
from .forms import UserUpdateForm, ProfileUpdateForm 
from django.urls import reverse, reverse_lazy

# PDF convertion
from io import BytesIO
import os
from django.conf import settings
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

#Dashboards and graphs
from math import pi

import pandas as pd
import numpy as np

from bokeh.io import output_file, show
from bokeh.embed import components
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.palettes import (Spectral6, Magma, Viridis, Plasma, 
                            Cividis, Category10, Category20, Category20b,
                            Category20c)
from bokeh.plotting import figure
from bokeh.transform import cumsum





# Beneficiaries Status Count 
@login_required
def profile_dash(request):
    actives = 0
    article20 = 0
    inactives = 0
    deceased = 0
    counts = []
    status = ['Active', 'Article 20.3', 'Inactive', 'Deceased']
    count = Beneficiary.objects.values()
    
    for i in count:
        if 'Active' in i.values():
            actives += 1
        elif 'Article 20.3' in i.values():
            article20 += 1
        elif 'Inactive' in i.values():
            inactives += 1
        elif 'Deceased' in i.values():
            deceased += 1 
    counts.extend([actives, article20, inactives, deceased])
    
    x = {}
    
    for key in status:
        for value in counts:
            x[key] = value
            counts.remove(value)
            break 
    
    data = pd.Series(x).reset_index(name='value').rename(columns={'index':'status'})
    data['angle'] = data['value']/data['value'].sum() * 2*pi
    data['color'] = ['green','gray','orange','red']
    color = ['green', 'gray', 'orange', 'red']

    data_csv = data.to_csv(index=True)
    
    fonts=['<i>italics</i>',
                '<pre>pre</pre>',
                '<b>bold</b>',
                '<small>small</small>',
                '<del>del</del>'
                ]
    
    hover = HoverTool(
        tooltips="""
        <div>
            <div>
                <span style="font-size: 17px; font-weight: bold; color:#966;"> <i>Status: @status</i></span>
            </div>
            <div>
                <!--<span>@fonts{safe}</span> -->
            </div>
            <div>
                <span style="font-size: 15px; font-weight: bold;">Total: @value</span>
            </div>
        </div>
        """
    )

    p = figure(plot_height=400, plot_width =750, title="Beneficiaries Count by Status", toolbar_location=None,
            tools=[hover], x_range=(-1, 1))
    
    p.outline_line_color = None
    p.title.text_font_size = '14pt'
    p.title.align = 'center'
    p.xaxis.major_label_text_font_size = '12px'
    p.xgrid.visible = False
    p.ygrid.visible = False
    p.axis.visible = False
    
    p.annular_wedge(x=0, y=1,  inner_radius=0.21, outer_radius=0.39, direction="anticlock",
            start_angle=cumsum('angle', include_zero=True), end_angle=cumsum('angle'),
            line_color="white", fill_color='color', fill_alpha = 0.6, legend_field='status', source=data)
    
    p.legend.orientation = "vertical"
    p.legend.location = "top_left"
    
    script1, div1 = components(p)
    
    # Member Status counts
    m_actives = 0
    suspend = 0
    terminate = 0
    deceased = 0
    m_counts = []
    m_status = ['Active', 'Suspended', 'Terminated', 'Deceased']
    m_count = Profile.objects.values()
    
    for i in m_count:
        if 'Active' in i.values():
            m_actives += 1
        elif 'Suspended' in i.values():
            suspend += 1
        elif 'Terminated' in i.values():
            terminate += 1
        elif 'Deceased' in i.values():
            deceased += 1 
    m_counts.extend([m_actives, suspend, terminate, deceased])
    
    # Benefiacuary QS to pandas and csv   
    qs2 = Beneficiary.objects.all()
    q2 = qs2.values('name', 'birth_date', 'beneficiary_type','beneficiary_status')
    df_ben = pd.DataFrame.from_records(q2)
    
    df_type = df_ben[['beneficiary_type']].value_counts()
    ben_csv = df_ben.to_csv(r'ben.csv')
    
    # Members Queryset to pandas and csv    
    qs1 = Profile.objects.all()
    q1 = qs1.values('shortname','birth_date','status')
    df_member = pd.DataFrame.from_records(q1)
    member_csv = df_member.to_csv(r'member.csv')
    
    
    x1 = {}
    
    for key in m_status:
        for value in m_counts:
            x1[key] = value
            m_counts.remove(value)
            break 


    data1 = pd.Series(x1).reset_index(name='value').rename(columns={'index':'m_status'})
                                                        
    data1['angle'] = data1['value']/data1['value'].sum() * 2*pi
    data1['color'] = ['green','gray','orange','red']#Category20c[len(x)
    
    fonts=['<i>italics</i>',
                '<pre>pre</pre>',
                '<b>bold</b>',
                '<small>small</small>',
                '<del>del</del>'
                ]
    
    hover = HoverTool(
        tooltips="""
        <div>
            <div>
                <span style="font-size: 17px; font-weight: bold; color:#966;"> <i> Status: @m_status</i></span>
            </div>
            <div>
                <!--<span>@fonts{safe}</span> -->
            </div>
            <div>
                <span style="font-size: 15px; font-weight: bold; ">Total: @value</span>
            </div>
        </div>
        """
    )

    p1 = figure(plot_height=400, plot_width =750, title="Members Count by Status", toolbar_location=None,
        tools=[hover], x_range=(-1, 1))
    
    p1.outline_line_color = None
    p1.title.align = 'center'
    p1.title.text_font_size = '14pt'
    p1.xaxis.major_label_text_font_size = '12px'
    p1.xgrid.visible = False
    p1.ygrid.visible = False
    p1.axis.visible = False

    p1.annular_wedge(x=0, y=1,  inner_radius=0.21, outer_radius=0.39, direction="anticlock",
            start_angle=cumsum('angle', include_zero=True), end_angle=cumsum('angle'),
            line_color="white", fill_color='color', fill_alpha = 0.6, legend_field='m_status', source=data1)
    
    p1.legend.orientation = "vertical"
    p1.legend.location = "top_left"
    
    script2, div2 = components(p1)

    # Beneficiary Dataframe
    df = pd.read_csv('ben.csv')
    df = df.drop(df[df.beneficiary_status =="Deceased"].index)
    df = df.drop(df[df.beneficiary_status =="Inactive"].index)
    
    # Member Dataframe
    df1 = pd.read_csv('member.csv')

    df1 = df1.drop(df1[df1.status =="Deceased"].index)
    df1 = df1.drop(df1[df1.status =="Terminated"].index)
    
    # Beneficiary age calculate
    def age(born):
        born = datetime.strptime(born, "%Y-%m-%d").date()
        today = date.today()
        return today.year - born.year                                         

    df['age'] = df['birth_date'].apply(age)
    df1['member_age'] = df1['birth_date'].apply(age)

    # Beneficiary Age groups definition    
    conditions = [
        (df['age'] < 18),
        (df['age'] < 36),
        (df['age'] < 50),
        (df['age'] < 60),
        (df['age'] < 70),
        (df['age'] < 80),
        (df['age'] < 90),
        (df['age'] < 100),
        (df['age'] > 99),
        ]

    values = ['Age(01 - 17)', 'Age(18 - 35)', 
            'Age(35 - 49)', 'Age(51 - 59)',
            'Age(60 - 69)', 'Age(70 - 79)',
            'Age(80 - 89)','Age(90 - 99)', 'Centenarians(100+))',
            ]

    df['age_group'] = np.select(conditions, values)

    ben_age_groups = df['age_group'].value_counts().sort_index(ascending=True)
    ben_age_groups = pd.DataFrame({'age_group':ben_age_groups.index, 'counts':ben_age_groups.values})
    # End Beneficiary age groups definition
    # Start member age groups definition
    conditions = [
        (df1['member_age'] < 50),
        (df1['member_age'] < 55),
        (df1['member_age'] < 60),
        (df1['member_age'] < 70),
        (df1['member_age'] < 80),
        (df1['member_age'] < 90),
        (df1['member_age'] <100),
        (df1['member_age'] > 99),
        ]

    values = ['Age(49 or less)', 'Age(50 - 54)',
            'Age(55 - 59)','Age(60 - 69)',
            'Age(70- 79)','Age(80 - 89)',
            'Age(90 - 99)', 'Centenarians(100+)',
            ]

    df1['m_age_group'] = np.select(conditions, values)

    
    m_age_groups = df1['m_age_group'].value_counts().sort_index(ascending=True)
    m_age_groups = pd.DataFrame({'m_age_group':m_age_groups.index, 'm_counts':m_age_groups.values})

    # Bokeh plotting Member & Beneficiary Age Groups
    ages = ben_age_groups['age_group']
    counts = ben_age_groups['counts']
    
    # Bokeh plotting for Members Age groups
    m_ages = m_age_groups['m_age_group']
    m_counts = m_age_groups['m_counts']
    
    source = ColumnDataSource(data=dict(ages=ages, counts=counts, color=Category20c[len(ben_age_groups)]))
    source1 = ColumnDataSource(data=dict(m_ages=m_ages, m_counts=m_counts, color=Category10[len(m_age_groups)]))
    
    fonts=['<i>italics</i>',
                '<pre>pre</pre>',
                '<b>bold</b>',
                '<small>small</small>',
                '<del>del</del>'
                ]
    
    hover = HoverTool(
        tooltips="""
        <div>
            <div>

templates/pmlprofile/cert-output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{}} Certificate</title>

    <style>
        @page{
            size:"A4";
            style:2.5cm 1.5cm 3.5cm 1.5cm;
            @top-center{
                content:"Progress Men's League"
            }
        }

    </style>
</head>
<body>
    
</body>
</html>

templates/pmlprofile/committee_create.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}| Add Committee{% endblock title %}


{% block content%}

<div class="content-wrapper">  

    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1>Committee Incumbents Creation </h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'pmlprofile:profiles' %}">Home</a></li>
                <li class="breadcrumb-item active">Add Incumbent </li>
            </ol>
            </div>
        </div>
        </div><!-- /.container-fluid -->
    </section>

<section class="content">  
        <div class="row">
        <!-- left column -->
    {% if user.is_staff %}
      

        <div class="col-md-6 mx-auto">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Add Committee</h3>
                </div>
                <div class="pl-3 pr-3">
                    <form action=""  method="POST">
                            {% csrf_token %}
                            {{form|crispy}}                   
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block">Add</button>
                            </div>
                    </form>
                </div>
                <!-- /.card-header-->
            </div>
        </div>
        {% else %}
        
        <div class="col-md-6 mx-auto ">
            <div class="jumbotron">
                <h2> <span class='text-danger'> Embagored!!</span>You are not authorised to edit this page.</h2>
                <a href="{% url 'pmlprofile:committees' %}">Go Back</a>
            </div>
          </div>
        
        
        {% endif %}
        

    </div> 
</section>
</div>

{% endblock %}

templates/pmlprofile/incumbent_form.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}| Update Committee {% endblock title %}


{% block content%}

<div class="content-wrapper">  

    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1>Update {{object.committee}} </h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'pmlprofile:committees' %}">Committees</a></li>
                <li class="breadcrumb-item active">Edit Incumbent </li>
            </ol>
            </div>
        </div>
        </div><!-- /.container-fluid -->
    </section>

<section class="content">  
        <div class="row">
        <!-- left column -->
    {% if user.is_staff %}

        <div class="col-md-6 mx-auto">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Update Committee</h3>
                </div>
                <div class="pl-3 pr-3">
                    <form action=""  method="POST">
                            {% csrf_token %}
                            {{form.member|as_crispy_field}} 
                            {{form.portfolio|as_crispy_field}} 
                            {{form.term_starts|as_crispy_field}}
                            {{form.term_ends|as_crispy_field}}                       
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block">Update</button>
                            </div>
                    </form>
                </div>
                <!-- /.card-header-->
            </div>
        </div>
        {% else %}
        
        <div class="col-md-6 mx-auto ">
            <div class="jumbotron">
                <h2> <span class='text-danger'> Embagored!!</span>You are not authorised to edit this page.</h2>
                <a href="{% url 'pmlprofile:committees' %}">Go Back</a>
            </div>
          </div>
        
        
        {% endif %}
        

    </div> 
</section>
</div>

{% endblock %}

templates/pmlprofile/profile_details.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}-{{profile_detail.shortname}} Profile{% endblock title %}
<style>
a.disabled {
  /* Make the disabled links grayish*/
  color: gray;
  /* And disable the pointer events */
  pointer-events: none;
}
</style>
{% block content %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6 text-right">
            <h1>Member Profile: {{profile_detail.user.last_name}} {{profile_detail.user.first_name}} {{profile_detail.middlename}} </h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'pmlprofile:profiles' %}">Membership</a></li>
              <li class="breadcrumb-item active">User Profile</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-info bg-light card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       src="{{profile_detail.photo.url}}"
                       alt="User profile picture">
                </div>

                <p class="text-muted text-center">Member Status:         
                    {% if profile_detail.status == 'Active' %}
                        <span class="text-info"> {{profile_detail.status}} </span> 
                    {% elif profile_detail.status == 'Deceased' %}
                        <span class="text-danger"> {{profile_detail.status}} </span> 
                    {%elif profile_detail.status == 'Suspended' or profile_detail.status == 'Terminated' %}
                        <span class="text-warning"> {{profile_detail.status}} </span> 
                    {% endif %}
                </p>  
                <p class="text-muted text-center">
                    <ul >
                        <li class="list-group-item" class="text-center"><i class="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{profile_detail.mobile_phone}} <br>
                            <a href="mailto:{{profile_detail.user.email}}"><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{profile_detail.user.email}}</a>
                        </li>
                    </ul>
                </p>      
                
                

                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <b>Date of Birth: <a class="float-right text-secondary">{{profile_detail.birth_date|date:'d M Y'}}</a> </b>
                    </li>
    
                </ul>

                
            </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-info bg-light">
                <div class="card-header">
                    <h3 class="card-title">Address Details</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <strong> {{profile_detail.address|safe}}</strong>
                <hr>
                <strong> {{profile_detail.town_city}} </strong>
                <hr>
                <strong> {{profile_detail.district_metro}}</strong>
                <hr>
                <strong> {{profile_detail.province}}</strong>
                {% if request.user.is_superuser %}
                <hr>
                <a href="{% url 'pmlprofile:membercert' profile_detail.id %}" class="btn btn-primary" target="_blank">Print Certificate</a>
                {% endif %}
              </div>
              <!-- /.card-body -->
            </div> 
            <!-- /.card -->
          </div>
          <!-- /.col -->  
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills ">
                  
                  <li class="nav-item nav-info"><a class="nav-link active" href="#timeline" data-toggle="tab">Beneficiaries</a></li>
                  
                </ul>
                </div><!-- /.card-header -->
                <div class="card-body">
                <div class="tab-content">
                
                    
            <div class=" active tab-pane" id="timeline">
                    
                <table class="table table-bordered">
                    <thead>
                  
                        <tr>
                        <th>Name </th>
                        <th>Relation</th>
                        <th>Date of Birth</th>
                        <th style="width: 40px">Status</th>
                        <th>Paid-up</th>
                        <th>Paid-up Date</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for beneficiary in profile_detail.beneficiaries.all %}
                        {% if beneficiary.beneficiary_status == 'Deceased' %}
                        <tr class="text-muted">     
                        <td>{{beneficiary.name}}</td>
                        <td>{{beneficiary.beneficiary_type}}</td>
                        <td>{{beneficiary.birth_date|date:'d - M - Y'}}</td>
                        <td>
                            <i class="fas fa-circle fa-2x text-red"></i>
                            </div>      
                        </td>
                        <!-- <td><span class="badge bg-danger">{{beneficiary.beneficiary_status}}</span></td> -->
                        <td>{% if beneficiary.is_paid %} Yes
                            {% else %} No
                            {% endif %}
                        </td>
                        <td>{{beneficiary.paid_date|date:'d F, Y'}}</td>                   
                        </tr>
                        <tr>
                        {% elif  beneficiary.beneficiary_status == 'Article 20.3' %}                               
                        <tr class="text-muted">     
                            <td>{{beneficiary.name}}</td>
                            <td>{{beneficiary.beneficiary_type}}</td>
                            <td>{{beneficiary.birth_date|date:'d - M - Y'}}</td>
                            <td>
                              <i class="fas fa-circle fa-2x text-secondary"></i>
                          </td>
                          <!-- <td><span class="badge bg-warning">{{beneficiary.beneficiary_status}}</span></td> -->
                            <td>{% if beneficiary.is_paid %} Yes
                            {% else %} No - Lapse Date: {{profile_detail.lapse_date|date:'d F, Y'}}</td> 
                            {% endif %}
                          </td>
                            <td>
                              <span class="badge bg-warning">
                                (Cover lapses in : {{profile_detail.lapse_date|timeuntil}})
                              </span>
                                                
                          </tr>
                        
                        
                        {% elif beneficiary.beneficiary_status == 'Inactive' %}
                        <tr> 
                          <tr class="text-muted">     
                            <td>{{beneficiary.name}}</td>
                            <td>{{beneficiary.beneficiary_type}}</td>
                            <td>{{beneficiary.birth_date|date:'d - M - Y'}}</td>
                            <td>
                              <i class="fas fa-circle fa-2x text-warning"></i>
                          </td>
                          <!-- <td><span class="badge bg-warning">{{beneficiary.beneficiary_status}}</span></td> -->
                              {% if beneficiary.is_paid %}  <td> Yes </td>
                                <td>{{beneficiary.paid_date|date:'d F, Y'}}</td>     
                              {% else %} 
                            <td>No </td> 
                            <td> Cover lapsed:<span class= "badge bg-warning">  {{profile_detail.lapse_date}}</span> </td>  
                            {% endif %}
                        
                                      
                          </tr>
                        
                        </tr>
                        {% else %}
                        <tr>     
                            <td>{{beneficiary.name}}</td>
                            <td>{{beneficiary.beneficiary_type}}</td>
                            <td>{{beneficiary.birth_date|date:'d - M - Y'}}</td>
                            <td>                                     
                                <i class="fas fa-circle fa-2x text-green"></i>
                                    
                        </div>

                            </td>
                            <!-- <td><span class="badge bg-success">{{beneficiary.beneficiary_status}}</span></td> -->
                            <td>{% if beneficiary.is_paid %} Yes
                                {% else %} No
                                {% endif %}
                              </td>
                                <td>
                                {% if beneficiary.is_paid %}
                                  {{beneficiary.paid_date|date:'d F, Y'}}
                                {% elif beneficiary_status == "Article 20.3" %}
                                  {{profile_detail.lapse_date}}   
                                {% endif %}                            
                              </td>                   
                            </tr>
                        <tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                    </table>         

                </div>

                <div class="tab-pane" id="settings" disabled="true">
                    <!-- The timeline -->
                    <div class="timeline timeline-inverse">
                    <!-- timeline time label -->
                    
                    <!-- /.timeline-label -->
                    <div class="tab-pane" id="settings">
                    
                    
                        <div class="col-md-12 mx-auto" > 
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3595.5430564937187!2d28.737803115631802!3d-25.686437883671008!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1eeaab94f3f19a2b%3A0xf4b06cc2174fe136!2s4103%20Section%20B%2C%20Ekangala%20B%2C%20Ekangala%2C%201021!5e0!3m2!1sen!2sza!4v1624665851568!5m2!1sen!2sza" 
                            width="950" height="500" style="border:0;" allowfullscreen="" loading="lazy">
                            </iframe>
                           <!-- <iframe src="https://www.google.com/maps/embed?pb={{profile_detail.address}}" width="950" height="500" style="border:0;" allowfullscreen="" loading="lazy"></iframe>  -->
                        </div>
                    </div>
          
                </div>
                </div>              
                </div>
                
                </div>
            </div>
        
        </div>
        </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">  
        
            </div>
            <div class="col-sm-12">
            <div class="jumbotron text-center">
                <h3>Legend: Beneficiary Status</h3> 
                <i class="fas fa-circle fa-2x text-green text-small mr-2"></i>Active  &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i class="fas fa-circle fa-2x text-red text-small mr-2"></i>Deceased
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i class="fas fa-circle fa-2x text-secondary text-small mr-2"></i>Article 20.3
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i class="fas fa-circle fa-2x text-warning text-small mr-2"></i>Inactive
            </div>
        </div>
        </div>
    </div><!-- /.container-fluid -->
    </section>

</div>
<!-- /.content-wrapper -->




{% endblock content %}