events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('meeting_list/',views.MeetingList.as_view(), name='meetings'),
    path('meeting_detail/<int:pk>/',views.MeetingDetail.as_view(), name='meeting'),
    path('meeting_create/',views.MeetingCreateView.as_view(), name='meeting_create'),
    # path('meeting_update/',views.MeetingUpdate.as_view(), name='meeting_update'),   
    path('attendance/<int:pk>/',views.AttendanceListView.as_view(), name='attendance'),
    path('funerals/',views.FuneralList.as_view(), name='funerals'),
]

pml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pmlmain.urls')),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('pmlprofile/', include('pmlprofile.urls'), name='pmlprofile'),
    path('events/',include('events.urls'), name='events'),
    path('docs/', include('docs.urls'), name='docs'),
    path('geoApp/', include('geoApp.urls'), name='geoApp'),
    path('dash/', include('dash.urls'), name='dash'),
    path('pmlfin/', include('pmlfin.urls'), name='pmlfin'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
admin.site.site_header ='PML Admin Portal' 
admin.site.index_title ='Manage the PML Portal'

pmlprofile/urls.py
from django.urls import path
from .views import (ProfileListView, CommitteeListView, IncumbentUpdateView,
                    MyProfileView, ProfileCertView, BeneficiaryList, #MemberAccountView,
                    ProfileDetails, CommitteeDetail, IncumbentCreateView,
                    UserLoginAdminView,
                    )                
from .views import profile_update, pdfcert_view, membercert_view

from django.contrib.auth.decorators import login_required

app_name = 'pmlprofile'  

urlpatterns =[
    # path('member_list/',views.member_list_view, name='member_list'),
    path('beneficiaries/',BeneficiaryList.as_view(), name= 'beneficiaries'),
    path('profiles/',ProfileListView.as_view(), name = 'profiles'),
    path('profile_detail/<int:pk>/',ProfileDetails.as_view(), name='profile_detail'),
    path('my_profile/<int:pk>/',login_required(MyProfileView.as_view(template_name='pmlprofile/my_profile.html')), name='my_profile'),
    path('my_cert/<int:pk>/',ProfileCertView.as_view(), name='my_cert'),
    path('pdf_cert/<int:pk>',pdfcert_view, name='pdf_cert'),
    path('membercert/<int:pk>/',membercert_view, name='membercert'),
    path('user_logins/', UserLoginAdminView.as_view(), name='user_login_admin'),
    # path('profile_dash/',profile_dash, name='profile_dash'),
    # path('ben_dash/',ben_dash, name='ben_dash'),
    # path('member_accounts/', MemberAccountView.as_view(), name='member_accounts'),
    
    # path('pdf_certificate/', views.pdf_certificate, name='pdf-certificate'),
    # path('my_cert/pdf_cert/<int:pk>/',views.pdfcert_view, name='pdf_cert'),
    # path('profile/add/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile_update/',profile_update, name='profile_update'),
    path('committees/',CommitteeListView.as_view(), name = 'committees'),
    path('committees/<int:pk>/',CommitteeDetail.as_view(), name = 'committee_detail'),
    path('committee_create/', IncumbentCreateView.as_view(), name='committee_create'),
    path('committee_update/<int:pk>/', IncumbentUpdateView.as_view(), name='committee_update')
    # path('committee_update/')
]

events/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from pmlprofile.models import Profile, Beneficiary
from datetime import datetime, date
from django.urls import  reverse

class Meeting(models.Model):
    date = models.DateField()
    
    MEETINGS = [
        ('Quartely Meeting','Quartely Meeting'),
        ('Special Meeting','Special Meeting'),
        ('Year-end Function','Year-end Function'),
        ('Extraordinary Meeting','Extraordinary Meeting'),  
    ]
    meeting_type = models.CharField(max_length=200, choices=MEETINGS)
    host = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    alt_venue = models.CharField(max_length=300,blank=True, null=True)
    
    def __str__(self):
        return f'{self.meeting_type} held on {self.date}'

class Funeral(models.Model):
    date = models.DateField()
    bereaved_member = models.ForeignKey(Profile, on_delete=models.CASCADE)
    DECEASED_TYPE = [
        ('Member','Member') ,
        ('Beneficiary','Beneficiary'),
    ]
    deceased_type = models.CharField(max_length=100, choices=DECEASED_TYPE)
    deceased_member = models.OneToOneField(User,on_delete=models.CASCADE, null=True, blank=True)
    deceased_beneficiary = models.OneToOneField(Beneficiary, on_delete=models.CASCADE, null=True,blank=True)
    # deceased_member = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True, blank=True)
    venue = models.CharField(max_length=200)
    
    def __str__(self):
        return f'{self.date} at {self.venue}' 

class FuneralAttendance(models.Model):
    funeral = models.ForeignKey(Funeral, on_delete=models.CASCADE, related_name='attendances')
    member= models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='members')
    is_present = models.BooleanField(default=True)
    ABSENCE = [
        ('Family Commitment','Family Commitment'),
        ('Ill-Health','Ill-Health'),
        ('Work Commitment','Work Commitment'),
        ('Funeral Attendance','Funeral Attendance'),
    ]
    absence_reason = models.CharField(choices=ABSENCE, max_length=300, null=True, blank=True)
    
    def __str__(self):
        return f'Attendace of {self.funeral}\'s funeral - Member: {self.member} - Present: {self.is_present}'
    
class Attendance(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, related_name='attendances')
    member= models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='member')
    is_present = models.BooleanField(default=True)
    ABSENCE = [
        ('Family Commitment','Family Commitment'),
        ('Ill-Health','Ill-Health'),
        ('Work Commitment','Work Commitment'),
        ('Funeral Attendance','Funeral Attendance'),
    ]
    absence_reason = models.CharField(choices=ABSENCE, max_length=300, null=True, blank=True)
    
    def __str__(self):
        return f'{self.meeting} Member: {self.member} - Present: {self.is_present}'

events/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView                             
from django.views.generic.edit import UpdateView, CreateView
from .models import Meeting, Attendance, Funeral, FuneralAttendance

# Create your views here.

class MeetingList(ListView):
    model = Meeting
    context_object_name = 'meetings'
    template_name = 'events/meeting_list.html'
    
    ordering = ['-date',]
    
class FuneralList(ListView):
    model = Funeral
    context_object_name = 'funerals'
    template_name = 'events/funerals.html'


class MeetingDetail(DetailView):
    model = Meeting
    context_object_name = 'meeting'
    template_name = 'events/meeting_detail.html'

class MeetingCreateView(CreateView):
    model = Meeting
    success_url = reverse_lazy('events:meetings')
    fields = ('date','meeting_type','host','alt_venue')
    template_name = 'events/meeting_create.html'

class AttendanceListView(ListView):
    model = Attendance 
    context_object_name = 'register'
    template_name = 'events/meeting_attendance.html'
    
    def get_context_data(self,*args, **kwargs):
        context = super(AttendanceListView, self).get_context_data(*args,**kwargs)
        context['absent'] = Attendance.objects.filter(is_present='False')
        context['present'] = Attendance.objects.filter(is_present='True')
        return context
        
        # context['qmeeting'] = Attendance.objects.filter(meeting_type='Quarterly Meeting')
        

templates/events/funerals.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %} 

{% block content %} 

<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>PML Funerals List</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'pmlprofile:profiles' %}">Membership</a></li>
            <li class="breadcrumb-item active">Funerals</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">List of Funerals</h3>

        <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
        </button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
        </button>
        </div>
    </div>
    <div class="card-body p-0">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10%">Funeral Date</th>
                    <th style="width: 10%">  Bereaved Member</th>
                    <th style="width: 20%"> Deceased Type</th>
                    <th style="width: 20%">Deceased Name  </th>
                    <th style="width: 25%">Venue</th>     
                    <th style="width: 25%"> Details</th>
                </tr>
            </thead>
            <tbody>
                <tr>
            {% for funeral in funerals %}
                    <td>{{ funeral.date|date:'d F Y'}}</td>
                    
                    <td> {{funeral.bereaved_member}}</td>
                    <td> {{funeral.deceased_type}}</td>
                    <td>
                        {% if funeral.deceased_type == "Beneficiary" %}
                            {{funeral.deceased_beneficiary.name}} 
                        {% else %}
                            {{funeral.deceased_member}}
                        {% endif %}
                    </td>                                  
                    <td> {{funeral.venue}}</td>
                    <td class="project-actions">
                        <a class="btn btn-info btn-sm" href="">
                            <i class="fas fa-pencil-alt">
                            </i>
                        Attendance Register
                        </a>             
                    </td>
                </tr>   
        {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper 

{% endblock %}

templates/events/meeting_attendance.html
{% extends 'layout.html' %}

{% block title %} | Attendance Register{% endblock title %}

{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
<div class="container-fluid">
<div class="row mb-2">
    <div class="col-sm-6">
    <h1>Events Attendance  {{meeting}}</h1> 
    </div>
    <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'events:meetings' %}">Meetings </a></li>
        <li class="breadcrumb-item active">Attendance</li>
    </ol>
    </div>
</div>
</div><!-- /.container-fluid -->
</section>

<!-- Attendance register data table -->
<section class="content">
<div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                    <h3 class="card-title">Choose format for printing or column display</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>                    
                        <th>Event</th>
                        <th>Member</th>
                        <th>Is Present</th>
                        <th>Absence Reaason</th>
                        
                    </tr>
                    </thead>

                <tbody>
                {% for attendance in meeting.attendances.all %} 

                {% if attendance.is_present  %}
                    <tr>
                        <td>{{attendance.meeting}}</td>
                        <td>{{attendance.member.user.last_name}} {{attendance.member.user.first_name}} {{attendance.member.middlename}}</td>
                        <td>{{attendance.is_present}}</td>
                        <td>{{attendance.absence_reason}}</td>
                    </tr>
                {% else %}
                    <tr class="text-danger">
                        <td>{{attendance.meeting}}</td>
                        <td>{{attendance.member.user.last_name}} {{attendance.member.user.first_name}} {{attendance.member.middlename}}</td>
                        <td>{{attendance.is_present}}</td>
                        <td>{{attendance.absence_reason}}</td>
                    </tr>    

                {% endif %}

                    
                {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th>Event</th>
                        <th>Member</th>
                        <th>Is Present</th>
                        <th>Absence Reaason</th>
                    </tr>
                </tfoot>
                </table>
            </div>
        </div>
    </div>  
                
</div>
</div>

</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock content %}

templates/events/meeting_create.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}| Add Meeting {% endblock title %}


{% block content%}

<div class="content-wrapper">  

    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1>Meeting Creation </h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'events:meetings' %}">Home</a></li>
                <li class="breadcrumb-item active">Meeting</li>
            </ol>
            </div>
        </div>
        </div><!-- /.container-fluid -->
    </section>

<section class="content">  
        <div class="row">
        <!-- left column -->
    {% if user.is_staff %}
      

        <div class="col-md-6 mx-auto">
            <!-- general form elements -->
        <div class="pd-3">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Add Meeting</h3>
                </div>
                <div class="pl-3 pr-3">
                    <form action=""  method="POST">
                            {% csrf_token %}
                            {{form|crispy}}                   
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block">Add</button>
                            </div>
                    </form>
                </div>
            </div>

        </div>
            
        </div>
        {% else %}

        <div class="jumbotron">
            <h2> <span class='text-danger'> Embagored!! </span> </br>
                You are not authorised to edit this page.
            </h2>
            <a href="{% url 'events:meetings' %}">Go Back</a>
        </div>
        
        {% endif %}
        

    </div> 
</section>
</div>

{% endblock %}

templates/events/meeting_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}| Events Details{% endblock title %}


{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper"> 

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6 text-center">
                <h1>
                   Event Date: &nbsp;&nbsp; {{meeting.date|date:'jS F Y'}}
                    
                </h1> 
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'events:meetings' %}">Meetings</a></li>
                    <li class="breadcrumb-item active">{{meeting.meeting_type}}</li>
                </ol>
            </div>
        </div>
        <div class="row mt-2 mb-1">
            {% if meeting.host.user.last_name %}
            <p><b>Event Host:</b> {{meeting.host.user.last_name}} 
                    {{meeting.host.user.first_name}}
                {{meeting.host.middlename}}
            {% else %}
            <b>Event Host:</b> &nbsp;&nbsp;Executive Committee
            {% endif %}

            </p>
            <p> <b>Address: </b> &nbsp;&nbsp;&nbsp;&nbsp;
            {% if meeting.host.address %}
            {{meeting.host.address}} 
            {% else %}
            {{meeting.alt_venue}}
            {% endif %}
            
            </p>
            <p> <b>Town: </b> &nbsp;&nbsp; {{meeting.host.town_city}} </p> </br>
            <p> <b>Total Present: </b> &nbsp;&nbsp; {{present}} </p>
            <p> <b>Toal Absent</b> &nbsp;&nbsp; {{absent}} </p>
            <p> </p>

        </div>
    </div><!-- /.container-fluid -->

</section>

<section class="content">
<div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                    <h3 class="card-title">Choose format for printing or column display</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     
                    <tr>                
                        <th>Event</th>
                        <th>Member</th>
                        <th>Is Present</th>
                        <th>Absence Reaason</th>
                        
                    </tr>
                    </thead>

                <tbody>
                {% for attendance in meeting.attendances.all %} 

                {% if attendance.is_present  %}
                    <tr>
                        <td>{{attendance.meeting}}</td>
                        <td>{{attendance.member.user.last_name}} {{attendance.member.user.first_name}} {{attendance.member.middlename}}</td>
                        <td>{{attendance.is_present}}</td>
                        <td>{{attendance.absence_reason}}</td>
                    </tr>
                {% else %}
                    <tr class="text-danger">
                        <td>{{attendance.meeting}}</td>
                        <td>{{attendance.member.user.last_name}} {{attendance.member.user.first_name}} {{attendance.member.middlename}}</td>
                        <td>{{attendance.is_present}}</td>
                        <td>{{attendance.absence_reason}}</td>
                    </tr>    

                {% endif %}

                    
                {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th>Event</th>
                        <th>Member</th>
                        <th>Is Present</th>
                        <th>Absence Reaason</th>
                    </tr>
                </tfoot>
                </table>
            </div>
        </div>
    </div>  
                
</div>
</div>

</section>
</div>
<!-- Main content -->

<!-- /.content -->

<!-- /.content-wrapper -->


{% endblock content %}

templates/events/meeting_list.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %} 

{% block content %} 

<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>PML Meetings</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'pmlprofile:profiles' %}">Home</a></li>
            <li class="breadcrumb-item active">Meetings</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">List of PML Events</h3>

        <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
        </button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
        </button>
        </div>
    </div>
    <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
                <tr>
                    <th style="width: 1%">
                        #
                    </th>
                    <th style="width: 20%">
                        Event Type
                    </th>
                    <th style="width: 8%">
                        Date
                    </th>
                    <th style="width: 15%">
                        Host
                    </th>
                    <th style="width: 30%">
                        Venue
                    </th>
                   
                
                    {% comment %} <th style="width: 30%" class="project-actions text-right"> 
                        <a class="btn btn-success btn-sm" href="{% url 'events:meeting_create' %}">
                            <i class="fas fa-plus-circle">
                            </i>
                        <strong> Add Meeting</strong>
                        </a> 
                    </th>                 {% endcomment %}
                </tr>
            </thead>
            <tbody>
                <tr>
            {% for meeting in meetings %}
                    <td>
                        {{ meeting.id}}
                    </td>
                    <td>
                        <a href="{% url 'events:meeting' meeting.id %}">
                            {{meeting.meeting_type}}
                        </a>
                    </td>
                    <td>
                        {{meeting.date}}
                    </td>

                    <td>

                    {% if meeting.host.user.last_name %}
                        {{meeting.host.user.last_name}} {{meeting.host.user.first_name}}  {{meeting.host.middlename}} 
                    {% else %}
                        Executive Committee
                    {% endif %}
                    </td>  
                    
                    
                    <td>
                        {% if meeting.host.address %}
                        {{meeting.host.address}}
                        {% else %}
                        {{meeting.alt_venue}}
                        {% endif %} 
                    </td>
                     <td class="project-actions text-right"> 
                        {% comment %} <a class="btn btn-primary btn-sm" href="{% url 'events:meeting' meeting.id %}">
                            <i class="fas fa-folder">
                            </i>
                            View Details
                        </a> {% endcomment %}
                        <a class="btn btn-info btn-sm" href="{% url 'events:meeting' meeting.id %}">
                            <i class="fas fa-pencil-alt">
                            </i>
                        Attendance Register
                        </a> 
                    
                            
                    </td>
                </tr>   
        {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}